name: Deploy static content to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js and Authenticate
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: site

      - name: Set up Git and Deploy to GitHub Pages
        run: |
          cd site  # Navigate to the _site directory
          git init
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force "https://$GITHUB_ACTOR:${{ secrets.DEPLOY_TOKEN }}@github.com/${{ github.repository }}.git" main:gh-pages
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
